# tmux alias
#  set = set-option
#  bind = bind-key
#  unbind = unbind-key


# Change prefix key
unbind C-b
set -g prefix C-j
bind C-j send-prefix

# Change escape time
set -s escape-time 1

# Enable mouse support
set -g mouse on

# Start index at 1
set -g base-index 1
set -g pane-base-index 1

# Shift window index number
set -g renumber-windows on

# Avoid visual bug
set -g aggressive-resize on

# Change history limit
set -g history-limit 5000

# Split panes keeping current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

# Statusline
set -g status-interval 1
set -g status-left-length 100
set -g status-left " #(tmux -V) ||"
set -g status-justify "absolute-centre"
set -g window-status-current-format "Session:#S Window:#I Pane:#P > #{pane_current_command}#F"
set -g status-right-length 100
set -g status-right "|| %H:%M:%S "
