# Change prefix key
set -g prefix C-j
unbind C-b
bind C-j send-prefix

# Enable mouse support
set -g mouse on

# Start index at 1
set -g base-index 1
setw -g pane-base-index 1

# Split panes keeping current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"
